name: Upload Artifact to S3

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter the branch name'
        required: true
        default: 'main'
        type: string
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'dev2'
        type: string

env:
  S3BUCKET: devops-artifact-bkt

jobs:
  upload:
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.name }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_NAME }}
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION_NAME }}
      - name: Print Inputs
        run: "echo Deploying to ${{github.event.inputs.environment}} environment"
      - name: Set timestamp
        run: echo "TIMESTAMP=$(date -u '+%Y-%m-%d_%H-%M-%S_%Z')" >> $GITHUB_ENV
      
      - name: Print Commit SHA
        run: echo "Current Commit SHA=$GITHUB_SHA"

      - name: Set Artifact Version with Branch Name
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          ARTIFACT_VERSION="${{var.APP_PREFIX}}${BRANCH_NAME}-${GITHUB_SHA}.${{ env.TIMESTAMP }}"
          BUILDVERSION="${BRANCH_NAME}-${GITHUB_SHA}.${{ env.TIMESTAMP }}"
          ARTIFACT_NAME="${ARTIFACT_VERSION}.tar.gz"
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV  # Store for later steps
          echo "Artifact Name: $ARTIFACT_NAME"
          touch version.html
          echo "$BUILDVERSION"> version.html
          # Debugging: Check if file exists
          ls -l version.html || echo "version.html NOT FOUND!"
          tar -zcvf "$ARTIFACT_NAME" *
      - name: Print Version File Content
        run: |
          cat version.html
          #mv version.html $APP_HOME/public/
          tar -zcvf "$ARTIFACT_NAME" *

      - name: Upload to S3 with timestamp
        run: |
          aws s3 cp "$ARTIFACT_NAME" s3://${{ env.S3BUCKET }}/"$ARTIFACT_NAME"
