name: Upload Artifact to S3

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter the branch name'
        required: true
        default: 'main'
        type: string
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'dev2'
        type: string

#env:
#  S3BUCKET: devops-artifact-bkt
#  APP_PREFIX: cync_ror_

jobs:
  upload:
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.name }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_NAME }}
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION_NAME }}
      - name: Fetch AWS Parameter Store Values
        run: |
          #echo "CONFIG_S3_BUCKET=$(aws ssm get-parameter --name "/dev2/config_s3_bucket" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          #echo "REPORT_S3_BUCKET=$(aws ssm get-parameter --name "/dev2/report_s3_bucket" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "ARTIFACT_S3_BUCKET=$(aws ssm get-parameter --name "artifact_s3_bucket" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "ARTIFACT_S3_FOLDER=$(aws ssm get-parameter --name "artifact_s3_folder" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          #echo "DATABASE_YAMLFILE=$(aws ssm get-parameter --name "/dev2/database_yamlfile" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          #echo "RAILS_ENVIRONMENT=$(aws ssm get-parameter --name "/dev2/rails_environment" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          #echo "APP_HOME=$(aws ssm get-parameter --name "/dev2/app_home" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "APP_PREFIX=$(aws ssm get-parameter --name "app_prefix" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
      - name: printing the parameter store Values
        run: |
          #echo "CONFIG_S3_BUCKET=${CONFIG_S3_BUCKET}"
          #echo "REPORT_S3_BUCKET=${REPORT_S3_BUCKET}"
          echo "ARTIFACT_S3_BUCKET=${ARTIFACT_S3_BUCKET}"
          echo "ARTIFACT_S3_FOLDER=${ARTIFACT_S3_FOLDER}"
          #echo "DATABASE_YAMLFILE=${DATABASE_YAMLFILE}"
          #echo "RAILS_ENVIRONMENT=${RAILS_ENVIRONMENT}"
          #echo "APP_HOME=${APP_HOME}"
          echo "APP_PREFIX=${APP_PREFIX}"
      - name: Print Inputs
        run: "echo Deploying to ${{github.event.inputs.environment}} environment"
      - name: Set timestamp
        run: echo "TIMESTAMP=$(date -u '+%Y-%m-%d_%H-%M-%S_%Z')" >> $GITHUB_ENV
      
      - name: Print Commit SHA
        run: echo "Current Commit SHA=$GITHUB_SHA"

      - name: Set Artifact Version with Branch Name
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          ARTIFACT_VERSION="${APP_PREFIX}${BRANCH_NAME}-${GITHUB_SHA}.${TIMESTAMP}"
          BUILDVERSION="${BRANCH_NAME}-${GITHUB_SHA}.${TIMESTAMP}"
          ARTIFACT_NAME="${ARTIFACT_VERSION}.tar.gz"
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV  # Store for later steps
          echo "Artifact Name: $ARTIFACT_NAME"
          touch version.html
          echo "$BUILDVERSION"> version.html
          # Debugging: Check if file exists
          ls -l version.html || echo "version.html NOT FOUND!"
          tar -zcvf "$ARTIFACT_NAME" *
      - name: Print Version File Content
        run: |
          cat version.html
          #mv version.html $APP_HOME/public/
          tar -zcvf "$ARTIFACT_NAME" *

      - name: Upload to S3 with timestamp
        run: |
          aws s3 cp "$ARTIFACT_NAME" s3://$ARTIFACT_S3_BUCKET/$ARTIFACT_S3_FOLDER/"
