name: Upload Artifact to S3

on:
  push:
    branches:
      - main  # Change this as needed

env:
  S3BUCKET: devops-artifact-bkt
  APP_PREFIX: cync_ror_

jobs:
  upload:
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set timestamp
        run: echo "TIMESTAMP=$(date -u '+%Y-%m-%d_%H-%M-%S_%Z')" >> $GITHUB_ENV
      
      - name: Print Commit SHA
        run: echo "Current Commit SHA=$GITHUB_SHA"

      - name: Set Artifact Version with Branch Name
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          ARTIFACT_VERSION="${{env.APP_PREFIX}}${BRANCH_NAME}-${GITHUB_SHA}.${{ env.TIMESTAMP }}"
          ARTIFACT_NAME="${ARTIFACT_VERSION}.tar.gz"
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV  # Store for later steps
          echo "Artifact Name: $ARTIFACT_NAME"
          tar -zcvf "$ARTIFACT_NAME" *

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_NAME }}
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION_NAME }}

      - name: Upload to S3 with timestamp
        run: |
          aws s3 cp "$ARTIFACT_NAME" s3://${{ env.S3BUCKET }}/"$ARTIFACT_NAME"
