name: Upload Website

on:
  push:
    branches:
      - main
env: 
  S3BUCKET: devops-artifact-bkt
  
jobs:
  deploy:
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_NAME }}
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION_NAME }} 
      - name: Upload Artifact to s3
        run: aws s3 cp website s3://${{ env.S3BUCKET }}/website --recursive
      #- name: Deploy to S3
      #  uses: tpaschalis/s3-sync-action@master
      #  with:
      #    args: --acl public-read --follow-symlinks --delete
      #  env:
      #    AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      #    SOURCE_DIR: 'website'
