name: Upload Website

on:
  workflow_dispatch:
  push:
    branches:
      - dev
env:
  S3BUCKET: devops-artifact-bkt

jobs:
  deploy:
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload Artifact to S3
        run: |
          echo "Branch name is ${{ github.ref_name }}"
          echo "Build started on $(date)"
          #appPrefix="$APP_PREFIX"
          ls -l
          timestamp=$(date -u '+%Y-%m-%d_%H-%M-%S_%Z')
          echo "Printing the branch name ${{ vars.BRANCH_NAME }}"
          artifactversion="${appPrefix}${{ vars.BRANCH_NAME }}.$timestamp"
          artifactname="$artifactversion.tar.gz"
          npm install
          tar -zcvf "$artifactname" *- name: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_NAME }}
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION_NAME }}
      - name: upload to s3
        run: aws s3 cp "$artifactname" "s3://${{ env.S3BUCKET }}"
      - name: Deploying new code to application server
        run: |
          cd /home/ubuntu/cync-devops-ansible
          ansible-playbook playbooks/directory.yml -i dynamic-inventory/dev/aws_ec2.yml
